# Generated by Django 5.2.6 on 2025-09-13 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_lancamento', models.DateField()),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('duracao', models.DurationField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.album')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('musicas', models.ManyToManyField(to='streaming.musica')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistMusica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.musica')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.playlist')),
            ],
        ),
    ]
