# Generated by Django 5.2.6 on 2025-09-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='duracao',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
